### ISSUE TITLE
E-mail addresses brake with link_no_scheme option

### ISSUE THREAD

**Issue by damiansb** [asika32764/php-autolink#12]
Using the link_no_scheme option will create links after the @ on email addresses. 

Example:

`$linker = new Asika\Autolink\Autolink(['link_no_scheme' => 'https://']);`
`echo $linker->convert(' ... test@my-domain.com.br ... ');`

Output:
test@<a href="https://https://my-domain.com.br">my-domain.com.br</a>

**Comment by michaelrimbach** [comment]
@asika32764 any chance to get this issue fixed?

**Comment by asika32764** [comment]
Fixed https://github.com/asika32764/php-autolink/releases/tag/2.0.3
