### ISSUE TITLE
phpStan errors

### ISSUE THREAD

**Issue by craigh** [asika32764/php-autolink#14]
Hi there! Congrats on your 2.0.0 release! 🎉 

phpStan is now throwing errors

>  Static method Asika\Autolink\AutolinkStatic::convertEmail() invoked with 2 parameters, 0 required.

>  Static method Asika\Autolink\AutolinkStatic::convert() invoked with 2 parameters, 0 required.

on lines like this:

```php
        $html = AutolinkStatic::convertEmail($html, ['class' => 'email-link']);
        $html = AutolinkStatic::convert($html, ['class' => 'external-link']);
```

**Comment by craigh** [comment]
hmmm. 
1. create a basic symfony project
2. include php-autolink and [phpStan](https://phpstan.org) as dependency
3. add the code above in a controller or something.
4. run phpStan. We run at level 3

**Comment by craigh** [comment]
I think the problem is in your [docblock here](https://github.com/asika32764/php-autolink/blob/11aca40d83771beb35404960bc02c53f1226938a/src/AutolinkStatic.php#L14-L15)

**Comment by asika32764** [comment]
Thanks, it seems I can run phpstan in any project to test it.

Here is 2.0.1
https://github.com/asika32764/php-autolink/releases/tag/2.0.1

**Comment by craigh** [comment]
> Thanks, it seems I can run phpstan in any project to test it.

yup. We have it as a dev dependency in our project and run it in the ci build process. Its a great tool.

thanks!
