### ISSUE TITLE
convertEmail creates mailto-link including trailing point

### ISSUE THREAD

**Issue by epalmans** [asika32764/php-autolink#2]
great library! Very usefull.
Discovered a minor bug...

e.g.:
`"My emailaddress is blabla@domain.xyz."`
becomes
`"My emailaddress is <a href="mailto:blabla@domain.xyz.">blabla@domain.xyz.</a>"`

While I would expect:
`"My emailaddress is <a href="mailto:blabla@domain.xyz">blabla@domain.xyz</a>."`

**Comment by epalmans** [comment]
using $regex = "/[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i"; in asika\autolink\src\Autolink.php ln.104 (convertEmail function) seems to solve it.

eddie

**Comment by asika32764** [comment]
Thank you, I will test it.

**Comment by asika32764** [comment]
Fixed with 3a7bd0fa4aad551e6717c25f51ab2f1ba38f3b55
