### ISSUE TITLE
Issue with email linking "in between(salsan@lt.com). "

### ISSUE THREAD

**Issue by salsanej** [asika32764/php-autolink#5]
The following text is what i have used to test auto link of emails `"and emails are coming in between(salsan@lt.com). "` but it is being linked in wrong way. See the output below:

`"and again some emails are coming in <a href="mailto:between(salsan@lt.com).">between(salsan@lt.com).</a>"`

**Comment by asika32764** [comment]
Fixed with 5e509862bac9112430a14001314fd57d87944735
